/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial.txt.bancodehoras.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import residencial.txt.bancodehoras.model.MonitoraTxt;

/**
 *
 * @author Marcos Paulo
 */
public class CadMonitorasTxt extends JDialog {

    protected boolean telaMonitoras;
    MonitoraTxt monitora = new MonitoraTxt();
    DefaultTableModel modelo;
    String status = "Ativo";
    boolean click = false;
    public CadMonitorasTxt() {
        initComponents();
        modelo = (DefaultTableModel)tbMonitoras.getModel();
        modelo.setNumRows(0);
        preecheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        jcbStatus = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMonitoras = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Monitora:");

        tfNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jcbStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcbStatus.setText("Inativa");
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcbStatus))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbMonitoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Stratus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMonitoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMonitorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMonitoras);
        if (tbMonitoras.getColumnModel().getColumnCount() > 0) {
            tbMonitoras.getColumnModel().getColumn(0).setMinWidth(80);
            tbMonitoras.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbMonitoras.getColumnModel().getColumn(0).setMaxWidth(80);
            tbMonitoras.getColumnModel().getColumn(1).setResizable(false);
            tbMonitoras.getColumnModel().getColumn(2).setMinWidth(70);
            tbMonitoras.getColumnModel().getColumn(2).setPreferredWidth(70);
            tbMonitoras.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
       /*if(click){
            List<String> lista = new Monitora().listarMonitoras();
            for(int i = 0; i < lista.size(); i++){
                 String[] dados = lista.get(i).split(";");
                 if(dados[0].equals(tfNome.getText())){ 
                     JOptionPane.showMessageDialog(null, monitora.alterar(i));
                     break;
                 }
             }
       }*/
       
       salvarDados();
       
       
       
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        salvarDados();
    }//GEN-LAST:event_tfNomeActionPerformed

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        if(jcbStatus.isSelected()){
            status = "Inativo";
        }else{
            status = "Ativo";
        }
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void tbMonitorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMonitorasMouseClicked
        int linha = tbMonitoras.getSelectedRow();
        if(evt.getClickCount()==1){
            click = true;
            tfNome.setText(tbMonitoras.getValueAt(linha, 1).toString());
            
            if((tbMonitoras.getValueAt(linha, 2).toString().equals("Inativo"))){
                jcbStatus.setSelected(true);
                status = "Inativo";
            }else{
                jcbStatus.setSelected(false);
                status = "Ativo";
            }
        }
    }//GEN-LAST:event_tbMonitorasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbStatus;
    private javax.swing.JTable tbMonitoras;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    public void mostrarTela(){        
        setModal(true);         //A dialog tem que ser modal. S� pode retornar do setVisible ap�s ficar invis�vel.
        setLocationRelativeTo(null);
        setVisible(true);       //Mostramos a dialog e esperamos o usu�rio escolher alguma coisa.
    }
    
    public int codigo(int n){
        int codigo = n;
        codigo+=1; 
        return codigo;
    }
    
    public void preecheTabela(){
        List<String> lista = new MonitoraTxt().listarMonitoras();
        for(String monitora : lista) {
            String[] dados = monitora.split(";");
            
            modelo.addRow(new Object[]{           
                codigo(tbMonitoras.getRowCount()),
                dados[0],
                dados[1]});
        }
    }
    
    public void salvarDados(){
       monitora.setDados(tfNome.getText()+";"+status); 
       
        modelo.addRow(new Object[]{           
            codigo(tbMonitoras.getRowCount()),
            tfNome.getText(),
            status});

        JOptionPane.showMessageDialog(null, monitora.salvar());
        
        tfNome.setText("");       
        
    }
}
