/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial.txt.bancodehoras.view;

import residencial.txt.bancodehoras.view.MonitorHoraExtraTxt;
import residencial.txt.bancodehoras.model.BancoDeHorasTxt;
import residencial.db.bancodehoras.model.Monitora;
import residencial.txt.bancodehoras.util.Utilitarios;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Paulo
 */
public class PrincipalTxt extends javax.swing.JFrame {

    BancoDeHorasTxt banco = new BancoDeHorasTxt();
    DefaultTableModel modelo = null;
    Utilitarios util = new Utilitarios();
    public PrincipalTxt() {
        initComponents();
        modelo = (DefaultTableModel)tbDados.getModel();
        modelo.setNumRows(0);
        //setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        tfHoraSaida.setEditable(false);
        util.carregarMonitoras(cbMonitoras);
        preecheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbMonitoras = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tfData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tfHoraSaida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfQtdeHoras = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taJustificativa = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btCadMonitora = new javax.swing.JButton();
        btHoraExtra = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Banco de Horas");

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Monitoras:");

        jLabel1.setText("Data:");

        tfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataFocusLost(evt);
            }
        });
        tfData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDataKeyReleased(evt);
            }
        });

        jLabel2.setText("Tipo:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Tipo", "Crédito", "Débito" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Hora Saída:");

        tfHoraSaida.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfHoraSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfHoraSaidaFocusLost(evt);
            }
        });
        tfHoraSaida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfHoraSaidaKeyReleased(evt);
            }
        });

        jLabel4.setText("Qtde Horas:");

        tfQtdeHoras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfQtdeHoras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfQtdeHorasFocusLost(evt);
            }
        });
        tfQtdeHoras.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfQtdeHorasKeyReleased(evt);
            }
        });

        jLabel5.setText("Justificativa");

        taJustificativa.setColumns(20);
        taJustificativa.setRows(5);
        jScrollPane1.setViewportView(taJustificativa);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btCadMonitora.setText("Cadastrar Monitora");
        btCadMonitora.setPreferredSize(new java.awt.Dimension(125, 70));
        btCadMonitora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadMonitoraActionPerformed(evt);
            }
        });
        jPanel1.add(btCadMonitora);

        btHoraExtra.setText("Horas Extras");
        btHoraExtra.setPreferredSize(new java.awt.Dimension(125, 70));
        btHoraExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHoraExtraActionPerformed(evt);
            }
        });
        jPanel1.add(btHoraExtra);

        btSalvar.setText("Salvar");
        btSalvar.setPreferredSize(new java.awt.Dimension(125, 70));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tfHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tfQtdeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMonitoras, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHoraSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMonitoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfQtdeHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        tbDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Monitora", "Tipo", "Hora Saída", "Qtda Horas", "Justificativa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.setRowHeight(20);
        jScrollPane2.setViewportView(tbDados);
        if (tbDados.getColumnModel().getColumnCount() > 0) {
            tbDados.getColumnModel().getColumn(0).setMinWidth(100);
            tbDados.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbDados.getColumnModel().getColumn(0).setMaxWidth(100);
            tbDados.getColumnModel().getColumn(1).setMinWidth(250);
            tbDados.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbDados.getColumnModel().getColumn(1).setMaxWidth(250);
            tbDados.getColumnModel().getColumn(2).setMinWidth(50);
            tbDados.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbDados.getColumnModel().getColumn(2).setMaxWidth(50);
            tbDados.getColumnModel().getColumn(3).setMinWidth(90);
            tbDados.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbDados.getColumnModel().getColumn(3).setMaxWidth(90);
            tbDados.getColumnModel().getColumn(4).setMinWidth(90);
            tbDados.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbDados.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        if(cbTipo.getSelectedItem()=="Débito"){
            tfHoraSaida.setEditable(true);
            tfHoraSaida.requestFocus(true);
        }else{
            tfQtdeHoras.requestFocus(true);
            tfHoraSaida.setEditable(false);
        }
    }//GEN-LAST:event_cbTipoActionPerformed

    private void btCadMonitoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadMonitoraActionPerformed
        CadMonitorasTxt monitoras = new CadMonitorasTxt();
        monitoras.mostrarTela();
        if(monitoras.isActive()){
            cbMonitoras.removeAllItems();
            util.carregarMonitoras(cbMonitoras);
        }
    }//GEN-LAST:event_btCadMonitoraActionPerformed

    private void tfDataKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDataKeyReleased
       char[] c = tfData.getText().toCharArray();
       for (int i = 0; i < c.length; i++) {
           // verifica se o char não é um dígito
           if (Character.isDigit(c[i]) || c[i]=='/') {
               
               if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
                    String formata = tfData.getText();    
                    if (formata.length()==2){
                        formata = formata + "/";  
                        tfData.setText(formata);
                    }       

                    if (formata.length()==5){  
                        formata = formata + "/";  
                        tfData.setText(formata);  
                    }
                    while(formata.length()>10){
                        formata = formata.substring (0, formata.length()- 1);
                        tfData.setText(formata);
                    }
                }
               
           }else{
               tfData.setText(tfData.getText().substring(0, tfData.getText().length()- 1));
               break;
           }
       }
        
        
    }//GEN-LAST:event_tfDataKeyReleased

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(cbMonitoras.getSelectedItem().equals("Selecione uma Monitora")){
            JOptionPane.showMessageDialog(null,"Selecione a Monitora");
                        
        }else if(tfData.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite a Data");
            tfData.requestFocus(true);
            
        }else if(cbTipo.getSelectedItem().equals("Selecione o Tipo")){
            JOptionPane.showMessageDialog(null,"Selecione o Tipo");
            
        }else if(cbTipo.getSelectedItem().equals("Débito")&&tfHoraSaida.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite a Hora de Saída");
            tfHoraSaida.requestFocus(true);
                        
        }else if(tfQtdeHoras.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite a Quantidade de Horas");
            tfQtdeHoras.requestFocus(true);
            
        }else if(taJustificativa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Digite uma justificativa");
            taJustificativa.requestFocus(true);
            
        }else if(util.validaData(tfData.getText())){
            tfData.setText("");
            tfData.requestFocus(true);
        }else{
            
            if(tfHoraSaida.getText().isEmpty()){
                tfHoraSaida.setText(" ");
            }
            banco.setDados(tfData.getText()+";"
                +(String) cbMonitoras.getSelectedItem()+";"
                +(String) cbTipo.getSelectedItem()+";"
                +tfHoraSaida.getText()+";"
                +tfQtdeHoras.getText()+";"
                +taJustificativa.getText());        

            modelo.addRow(new Object[]{           
                tfData.getText(),
                (String) cbMonitoras.getSelectedItem(),
                (String) cbTipo.getSelectedItem(),
                tfHoraSaida.getText(),
                tfQtdeHoras.getText(),
                taJustificativa.getText()});

            JOptionPane.showMessageDialog(null, banco.salvar());
            
            tfData.setText("");
            cbMonitoras.setSelectedIndex(0);
            cbTipo.setSelectedIndex(0);
            tfQtdeHoras.setText("");
            tfHoraSaida.setText("");
            taJustificativa.setText("");
            
        }      
        
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btHoraExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHoraExtraActionPerformed
        MonitorHoraExtraTxt monitorHoraExtra = new MonitorHoraExtraTxt();
        monitorHoraExtra.mostrarTela();
        if(monitorHoraExtra.isActive()){
            cbMonitoras.removeAllItems();
            util.carregarMonitoras(cbMonitoras);
        }
    }//GEN-LAST:event_btHoraExtraActionPerformed

    private void tfHoraSaidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHoraSaidaKeyReleased
       char[] c = tfHoraSaida.getText().toCharArray();
       for (int i = 0; i < c.length; i++) {
           // verifica se o char não é um dígito
           if (Character.isDigit(c[i]) || c[i]==':') {
               
               if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
                    String formata = tfHoraSaida.getText();    
                    if (formata.length()==2){
                        formata = formata + ":";  
                        tfHoraSaida.setText(formata);
                    }       

                    while(formata.length()>5){
                        formata = formata.substring (0, formata.length()- 1);
                        tfHoraSaida.setText(formata);
                    }
                }
               
           }else{
               tfHoraSaida.setText(tfHoraSaida.getText().substring(0, tfHoraSaida.getText().length()- 1));
               break;
           }
       }
        
        
        
    }//GEN-LAST:event_tfHoraSaidaKeyReleased

    private void tfQtdeHorasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtdeHorasKeyReleased
        char[] c = tfQtdeHoras.getText().toCharArray();
        for (int i = 0; i < c.length; i++) {
            // verifica se o char não é um dígito
            if (Character.isDigit(c[i]) || c[i]==':') {

                if(evt.getKeyCode() != KeyEvent.VK_BACK_SPACE){
                     String formata = tfQtdeHoras.getText();    
                     if (formata.length()==2){
                         formata = formata + ":";  
                         tfQtdeHoras.setText(formata);
                     } 
                     
                     while(formata.length()>5){
                         formata = formata.substring (0, formata.length()- 1);
                         tfQtdeHoras.setText(formata);
                     }
                 }

            }else{
                tfQtdeHoras.setText(tfQtdeHoras.getText().substring(0, tfQtdeHoras.getText().length()- 1));
                break;
            }
        }
        
        
    }//GEN-LAST:event_tfQtdeHorasKeyReleased

    private void tfHoraSaidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfHoraSaidaFocusLost
        if(!tfHoraSaida.getText().isEmpty() && !util.validaHora(tfHoraSaida.getText())){
            JOptionPane.showMessageDialog(null,"Hora Inválida");
            tfHoraSaida.setText("");
            tfHoraSaida.requestFocus(true);
        }
    }//GEN-LAST:event_tfHoraSaidaFocusLost

    private void tfQtdeHorasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfQtdeHorasFocusLost
        if(!tfQtdeHoras.getText().isEmpty() && !util.validaHora(tfQtdeHoras.getText())){
            JOptionPane.showMessageDialog(null,"Hora Inválida");
            tfQtdeHoras.setText("");
            tfQtdeHoras.requestFocus(true);
        }
    }//GEN-LAST:event_tfQtdeHorasFocusLost

    private void tfDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataFocusLost
        
    }//GEN-LAST:event_tfDataFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalTxt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadMonitora;
    private javax.swing.JButton btHoraExtra;
    private javax.swing.JButton btSalvar;
    public javax.swing.JComboBox<String> cbMonitoras;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taJustificativa;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField tfData;
    private javax.swing.JTextField tfHoraSaida;
    private javax.swing.JTextField tfQtdeHoras;
    // End of variables declaration//GEN-END:variables

        
    public void preecheTabela(){
        String data, nome, tipo, horaSaida, qtdeHora, Justificativa;
        List<String> lista = banco.listarDados();
        for(String m : lista) {
            String[] dados = m.split(";");
            
            modelo.addRow(new Object[]{           
                dados[0],
                dados[1],
                dados[2],
                dados[3],
                dados[4],
                dados[5]});   
           
          
        }
    }
}
