/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial.db.bancodehoras.view;

import java.awt.Color;
import residencial.db.bancodehoras.model.Monitora;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marcos Paulo
 */
public class CadMonitoras extends JInternalFrame {

    protected boolean telaMonitoras;
    Monitora monitora = new Monitora();
    DefaultTableModel modelo;
    boolean click = false;
    public CadMonitoras() {
        initComponents();
        monitora.monitoraAtiva(tbMonitoras);
        btSalvar.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jcbStatus = new javax.swing.JCheckBox();
        btSalvar = new javax.swing.JButton();
        cbAtiva = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMonitoras = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Cadastro de Monitoras");
        setPreferredSize(new java.awt.Dimension(836, 698));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 180));
        jPanel1.setMinimumSize(new java.awt.Dimension(743, 288));
        jPanel1.setPreferredSize(new java.awt.Dimension(354, 380));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Monitora:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 338;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(tfNome, gridBagConstraints);

        jcbStatus.setBackground(new java.awt.Color(102, 0, 180));
        jcbStatus.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jcbStatus.setForeground(new java.awt.Color(255, 255, 255));
        jcbStatus.setText("Exibir Monitoras Inativas");
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jcbStatus, gridBagConstraints);

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residencial/db/images/salvar.png"))); // NOI18N
        btSalvar.setBorder(null);
        btSalvar.setBorderPainted(false);
        btSalvar.setPreferredSize(new java.awt.Dimension(125, 50));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        jPanel1.add(btSalvar, gridBagConstraints);

        cbAtiva.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        cbAtiva.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 257;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(cbAtiva, gridBagConstraints);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 0, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 93;
        gridBagConstraints.ipady = 92;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        tbMonitoras.setAutoCreateRowSorter(true);
        tbMonitoras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbMonitoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbMonitoras.setGridColor(new java.awt.Color(255, 255, 255));
        tbMonitoras.setRowHeight(30);
        tbMonitoras.setRowMargin(0);
        tbMonitoras.setSelectionBackground(new java.awt.Color(102, 0, 180));
        tbMonitoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMonitorasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMonitoras);
        if (tbMonitoras.getColumnModel().getColumnCount() > 0) {
            tbMonitoras.getColumnModel().getColumn(0).setMinWidth(80);
            tbMonitoras.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbMonitoras.getColumnModel().getColumn(0).setMaxWidth(80);
            tbMonitoras.getColumnModel().getColumn(1).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 777;
        gridBagConstraints.ipady = 162;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 180));
        jLabel8.setText("Cadastro de Monitoras");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(50, 50, 20, 0);
        getContentPane().add(jLabel8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        tfNome.setText("");
        cbAtiva.setSelectedIndex(0);
        if(jcbStatus.isSelected()){
            monitora.monitoraInativa(tbMonitoras);
        }else{
            monitora.monitoraAtiva(tbMonitoras);
        }
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void tbMonitorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMonitorasMouseClicked
        int linha = tbMonitoras.getSelectedRow();
        if(evt.getClickCount()==1){
            click = true;
            monitora.setMonitoraId(Integer.parseInt(tbMonitoras.getValueAt(linha, 0).toString()));
            tfNome.setText(tbMonitoras.getValueAt(linha, 1).toString());
            
            if(jcbStatus.isSelected()){
                cbAtiva.setSelectedIndex(1);
            }else{
                cbAtiva.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tbMonitorasMouseClicked

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if(!tfNome.getText().isEmpty()){
            insert();
        }else{
            JOptionPane.showMessageDialog(null, "Digite o nome da monitora");
            tfNome.requestFocus(true);
        }   
    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        insert();
    }//GEN-LAST:event_tfNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<String> cbAtiva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbStatus;
    private javax.swing.JTable tbMonitoras;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    //public void mostrarTela(){        
        //setModal(true);         //A dialog tem que ser modal. S� pode retornar do setVisible ap�s ficar invis�vel.
        //setLocationRelativeTo(null);
        //setVisible(true);       //Mostramos a dialog e esperamos o usu�rio escolher alguma coisa.
    //}
    
    public void insert(){        
        monitora.setNomeMonitora(tfNome.getText());
        monitora.setStatus((String) cbAtiva.getSelectedItem());        
        
        if(click){
            monitora.update();
        }else{
            monitora.insert();        
        }
        
        if(jcbStatus.isSelected()){
            monitora.monitoraInativa(tbMonitoras);
        }else{
            monitora.monitoraAtiva(tbMonitoras);
        }
        
        limparCampos();
    }
    
    public void limparCampos(){
        jcbStatus.setSelected(false);
        monitora.monitoraAtiva(tbMonitoras);
        tfNome.setText("");
        cbAtiva.setSelectedIndex(0);
        click = false;
    }
    
    
    /*
    LÊ AS LINHAS DO ARQUIVO DE TEXTO E ADICIONA NA TABLE
    public void preecheTabela(){
        List<String> lista = new Monitora().listarMonitoras();
        for(String monitora : lista) {
            String[] dados = monitora.split(";");
            
            modelo.addRow(new Object[]{           
                codigo(tbMonitoras.getRowCount()),
                dados[0],
                dados[1]});
        }
    }*/ 
    
    /*
    ADICIONA OS DADOS EM ARQUIVO DE TEXTO
    
    public void salvarDados(){
       monitora.setDados(tfNome.getText()+";"+status); 
       
        modelo.addRow(new Object[]{           
            codigo(tbMonitoras.getRowCount()),
            tfNome.getText(),
            status});

        JOptionPane.showMessageDialog(null, monitora.salvar());
        
        tfNome.setText("");       
        
    }*/
}
