/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial.db.bancodehoras.view;

import residencial.db.util.Utilitarios;
import java.awt.Color;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import residencial.db.bancodehoras.dao.BancoDeHoras;

/**
 *
 * @author Marcos Paulo
 */
public class MonitorHoraExtra extends JInternalFrame {

    DefaultTableModel modelo;
    Utilitarios util = new Utilitarios();
    BancoDeHoras banco = new BancoDeHoras();    
    boolean click = false;
    
    public MonitorHoraExtra() {
        initComponents();
        modelo = (DefaultTableModel)tbDados.getModel();
        modelo.setNumRows(0);
        lbStatus.setVisible(false);
        lbHoraExtra.setVisible(false);        
        util.preecheComboMonitora(cbMonitoras);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbMonitoras = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lbStatus = new javax.swing.JLabel();
        lbHoraExtra = new javax.swing.JLabel();

        tbDados.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Monitora", "Tipo", "Hora Saída", "Hora Entrada", "Qtda Horas", "Justificativa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDados.setRowHeight(20);
        tbDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDados);
        if (tbDados.getColumnModel().getColumnCount() > 0) {
            tbDados.getColumnModel().getColumn(0).setMinWidth(100);
            tbDados.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbDados.getColumnModel().getColumn(0).setMaxWidth(100);
            tbDados.getColumnModel().getColumn(1).setMinWidth(250);
            tbDados.getColumnModel().getColumn(1).setPreferredWidth(250);
            tbDados.getColumnModel().getColumn(1).setMaxWidth(250);
            tbDados.getColumnModel().getColumn(2).setMinWidth(80);
            tbDados.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbDados.getColumnModel().getColumn(2).setMaxWidth(80);
            tbDados.getColumnModel().getColumn(3).setMinWidth(90);
            tbDados.getColumnModel().getColumn(3).setPreferredWidth(90);
            tbDados.getColumnModel().getColumn(3).setMaxWidth(90);
            tbDados.getColumnModel().getColumn(4).setMinWidth(90);
            tbDados.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbDados.getColumnModel().getColumn(4).setMaxWidth(90);
            tbDados.getColumnModel().getColumn(5).setMinWidth(90);
            tbDados.getColumnModel().getColumn(5).setPreferredWidth(90);
            tbDados.getColumnModel().getColumn(5).setMaxWidth(90);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Monitora:");

        cbMonitoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbMonitorasMouseClicked(evt);
            }
        });
        cbMonitoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMonitorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbMonitoras, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbMonitoras, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbStatus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbStatus.setText("STATUS");

        lbHoraExtra.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbHoraExtra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHoraExtra.setText("00:00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbHoraExtra, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbStatus)
                .addGap(18, 18, 18)
                .addComponent(lbHoraExtra))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMonitorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMonitorasActionPerformed
        if (!cbMonitoras.getSelectedItem().equals("Selecione uma Monitora")) {
            String[] id = cbMonitoras.getSelectedItem().toString().split("-");
            banco.setMonitoraId(Integer.parseInt(id[0]));
            banco.listarDadosPorMonitora(tbDados,lbHoraExtra, lbStatus);
        }        

        if (tbDados.getRowCount() == 0) {
            lbStatus.setVisible(false);
            lbHoraExtra.setVisible(false);
        } else {
            lbStatus.setVisible(true);
            lbHoraExtra.setVisible(true);
        }
    }//GEN-LAST:event_cbMonitorasActionPerformed

    private void tbDadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDadosMouseClicked
        int linha = tbDados.getSelectedRow();
        if (evt.getClickCount() == 1) {
            click = true;
            String[] id = tbDados.getValueAt(linha, 1).toString().split("-");
            banco.setMonitoraId(Integer.parseInt(id[0]));
        }
    }//GEN-LAST:event_tbDadosMouseClicked

    private void cbMonitorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbMonitorasMouseClicked
        
    }//GEN-LAST:event_cbMonitorasMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbMonitoras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHoraExtra;
    private javax.swing.JLabel lbStatus;
    private javax.swing.JTable tbDados;
    // End of variables declaration//GEN-END:variables

   // public void mostrarTela(){        
      //  setModal(true);         //A dialog tem que ser modal. S� pode retornar do setVisible ap�s ficar invis�vel.
       // setLocationRelativeTo(null);
       //setVisible(true);       //Mostramos a dialog e esperamos o usu�rio escolher alguma coisa.
   // }  
    
    
    /*public void calculaHoraExtra(){
        int horaExtra = 0,
            minutoExtra = 0,
            horaCredito = 0,
            minutoCredito = 0,
            horaDebito = 0,
            minutoDebito = 0,
            horaAux = 0,
            minutoAux = 0;
        
        modelo.setNumRows(0);
        List<String> lista = bancoHoras.listarDados();
        for(String m : lista) {
            
                
                //PEGA A QUANTIDADE DE HORAS                
                horaString = dados[4].substring(0,2);
                minutoString = dados[4].substring(3,5);

                
                
                if(dados[2].equals("Crédito")){
                    horaAux = Integer.parseInt(horaString);
                    minutoAux = Integer.parseInt(minutoString);
                    horaCredito+=horaAux;
                    minutoCredito+=minutoAux;
                    //System.out.println("hora somada: "+horaExtra+":"+minutoExtra);
                }else{
                    horaAux = Integer.parseInt(horaString);
                    minutoAux = Integer.parseInt(minutoString);
                    horaDebito+=horaAux;
                    minutoDebito+=minutoAux;
                   //System.out.println("hora subtraida: "+horaExtra+":"+minutoExtra);
                }               
                
                if(minutoCredito>=60){
                    horaCredito+=1;
                    minutoCredito = minutoCredito - 60;
                }
                
                if(minutoDebito>=60){
                    horaDebito+=1;
                    minutoDebito = minutoDebito - 60;
                }
                                               
                 
            }
        
        lista.clear();
        
        horaExtra = horaCredito - horaDebito;
        minutoExtra = minutoCredito - minutoDebito;
        
        if(minutoExtra<0){
            horaExtra-=1;
            minutoExtra = minutoExtra - (-60);
        }
        
        horaString = String.valueOf(horaExtra);
        minutoString = String.valueOf(minutoExtra);
                
        if(horaExtra>-10){
            if(horaExtra<0){
                horaString = String.valueOf(horaExtra*(-1));
                horaString = "-0"+horaString;
                System.out.println(horaString);
            }
            
            if(horaExtra>0 && horaExtra<10){
                horaString = "0"+horaString;
            }
            
        }
               
        
        if(minutoExtra<10){
            minutoString = "0"+minutoString;
        }
        
        if(horaExtra<0){
            lbHoraExtra.setForeground(Color.red);
            lbStatus.setText("DÉBITO");
            lbStatus.setForeground(Color.red);
        }else{
            lbHoraExtra.setForeground(new Color(0,153,51));
            lbStatus.setText("CRÉDITO");
            lbStatus.setForeground(new Color(0,153,51));
        }
        
        lbHoraExtra.setText(horaString+":"+minutoString);
        
    }*/

    
    
    
        
}
