/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package residencial.db.bancodehoras.view;

import java.awt.Color;
import java.awt.Insets;
import java.beans.PropertyVetoException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Marcos Paulo
 */
public class ResidencialIasp extends javax.swing.JFrame {

    MonitorHoraExtra monitor;
    CadMonitoras cadMonitoras;
    CadHoraExtra cadHoraExtra;
    public ResidencialIasp() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelMenu = new javax.swing.JPanel();
        panelBotoes = new javax.swing.JPanel();
        panelHoraExtra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btCadHoraExtra = new javax.swing.JLabel();
        panelMonitoras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btCadMonitoras = new javax.swing.JLabel();
        panelMonitorHoras = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btMonitorHoraExtra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deskTop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 153));
        setUndecorated(true);

        panelMenu.setBackground(new java.awt.Color(102, 0, 153));

        panelBotoes.setBackground(new java.awt.Color(102, 0, 153));
        panelBotoes.setPreferredSize(new java.awt.Dimension(265, 210));
        panelBotoes.setLayout(new java.awt.GridBagLayout());

        panelHoraExtra.setBackground(new java.awt.Color(102, 0, 153));
        panelHoraExtra.setPreferredSize(new java.awt.Dimension(300, 60));
        panelHoraExtra.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residencial.db.images/entrada.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(60, 50));
        panelHoraExtra.add(jLabel2, new java.awt.GridBagConstraints());

        btCadHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadHoraExtra.setForeground(new java.awt.Color(255, 255, 255));
        btCadHoraExtra.setText("Cadastrar Hora Extra");
        btCadHoraExtra.setPreferredSize(new java.awt.Dimension(240, 60));
        btCadHoraExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadHoraExtraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadHoraExtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCadHoraExtraMouseExited(evt);
            }
        });
        panelHoraExtra.add(btCadHoraExtra, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelBotoes.add(panelHoraExtra, gridBagConstraints);

        panelMonitoras.setBackground(new java.awt.Color(102, 0, 153));
        panelMonitoras.setPreferredSize(new java.awt.Dimension(300, 60));
        panelMonitoras.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residencial.db.images/entrada.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(60, 50));
        panelMonitoras.add(jLabel1, new java.awt.GridBagConstraints());

        btCadMonitoras.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btCadMonitoras.setForeground(new java.awt.Color(255, 255, 255));
        btCadMonitoras.setText("Cadastrar Monitoras");
        btCadMonitoras.setPreferredSize(new java.awt.Dimension(240, 60));
        btCadMonitoras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btCadMonitorasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btCadMonitorasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btCadMonitorasMouseExited(evt);
            }
        });
        panelMonitoras.add(btCadMonitoras, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        panelBotoes.add(panelMonitoras, gridBagConstraints);

        panelMonitorHoras.setBackground(new java.awt.Color(102, 0, 153));
        panelMonitorHoras.setPreferredSize(new java.awt.Dimension(300, 60));
        panelMonitorHoras.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/residencial.db.images/entrada.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(60, 50));
        panelMonitorHoras.add(jLabel3, new java.awt.GridBagConstraints());

        btMonitorHoraExtra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btMonitorHoraExtra.setForeground(new java.awt.Color(255, 255, 255));
        btMonitorHoraExtra.setText("Monitor de Hora Extra");
        btMonitorHoraExtra.setPreferredSize(new java.awt.Dimension(240, 60));
        btMonitorHoraExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btMonitorHoraExtraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btMonitorHoraExtraMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btMonitorHoraExtraMouseExited(evt);
            }
        });
        panelMonitorHoras.add(btMonitorHoraExtra, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        panelBotoes.add(panelMonitorHoras, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sair");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        deskTop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout deskTopLayout = new javax.swing.GroupLayout(deskTop);
        deskTop.setLayout(deskTopLayout);
        deskTopLayout.setHorizontalGroup(
            deskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 766, Short.MAX_VALUE)
        );
        deskTopLayout.setVerticalGroup(
            deskTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(deskTop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deskTop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadMonitorasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadMonitorasMouseEntered
        panelMonitoras.setBackground(new Color(102,0,180));
    }//GEN-LAST:event_btCadMonitorasMouseEntered

    private void btCadMonitorasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadMonitorasMouseExited
        panelMonitoras.setBackground(new Color(102,0,153));
    }//GEN-LAST:event_btCadMonitorasMouseExited

    private void btCadHoraExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadHoraExtraMouseEntered
        panelHoraExtra.setBackground(new Color(102,0,180));
    }//GEN-LAST:event_btCadHoraExtraMouseEntered

    private void btCadHoraExtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadHoraExtraMouseExited
        panelHoraExtra.setBackground(new Color(102,0,153));
    }//GEN-LAST:event_btCadHoraExtraMouseExited

    private void btMonitorHoraExtraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMonitorHoraExtraMouseEntered
        panelMonitorHoras.setBackground(new Color(102,0,180));
    }//GEN-LAST:event_btMonitorHoraExtraMouseEntered

    private void btMonitorHoraExtraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMonitorHoraExtraMouseExited
        panelMonitorHoras.setBackground(new Color(102,0,153));
    }//GEN-LAST:event_btMonitorHoraExtraMouseExited

    private void btCadMonitorasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadMonitorasMouseClicked
        if (cadMonitoras == null){

            cadMonitoras = new CadMonitoras();
            deskTop.moveToFront(cadMonitoras);
            deskTop.add(cadMonitoras);

        }else
        deskTop.moveToFront(cadMonitoras);
        //monitor.desabilitaCampos();
        //}
        try {
            cadMonitoras.setMaximum(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
        cadMonitoras.setVisible(true);
        cadMonitoras.setBorder(new EmptyBorder(new Insets(-25,0,0,0)));
    }//GEN-LAST:event_btCadMonitorasMouseClicked

    private void btCadHoraExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadHoraExtraMouseClicked
        if (cadHoraExtra == null){

            cadHoraExtra = new CadHoraExtra();
            deskTop.moveToFront(cadHoraExtra);
            deskTop.add(cadHoraExtra);

        }else
        deskTop.moveToFront(cadHoraExtra);
        //monitor.desabilitaCampos();
        //}
        try {
            cadHoraExtra.setMaximum(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
        cadHoraExtra.setVisible(true);
        cadHoraExtra.setBorder(new EmptyBorder(new Insets(-25,0,0,0)));
        ((BasicInternalFrameUI) cadHoraExtra.getUI()).setNorthPane(null);
    }//GEN-LAST:event_btCadHoraExtraMouseClicked

    private void btMonitorHoraExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btMonitorHoraExtraMouseClicked
        if (monitor == null){

            monitor = new MonitorHoraExtra();
            deskTop.moveToFront(monitor);
            deskTop.add(monitor);

        }else
        deskTop.moveToFront(monitor);
        //monitor.desabilitaCampos();
        //}
        try {
            monitor.setMaximum(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
        monitor.setVisible(true);
        monitor.setBorder(new EmptyBorder(new Insets(-25,0,0,0)));
    }//GEN-LAST:event_btMonitorHoraExtraMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResidencialIasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResidencialIasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResidencialIasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResidencialIasp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResidencialIasp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btCadHoraExtra;
    private javax.swing.JLabel btCadMonitoras;
    private javax.swing.JLabel btMonitorHoraExtra;
    private javax.swing.JDesktopPane deskTop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelHoraExtra;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelMonitorHoras;
    private javax.swing.JPanel panelMonitoras;
    // End of variables declaration//GEN-END:variables
}
